name : 'Custom Github Action'
description: 'takes number and return the squared number'
inputs:
  num:
    required: true
    default: "1"
  outputs:
    num_squared:
      value: ${{}}
      
  runs:
    using: 'composite'
    steps:
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r  requirements.txt
        shell: bash
      - name: Pass Inputs to Shell
        run: |
          echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB.ENV
        shell: bash
      - name: Fetch the number's square
        id: get-square
        run: python src/get_num_square.py
        shell: bash
